feat: zmenšiť/zvačšiť na desktope
SlovakNationalGallery/umenie-mesta-bratislavy pull request #34
Opened 2023-06-08 13:03 UTC by FrantisekMichalSebestyen

https://github.com/SlovakNationalGallery/umenie-mesta-bratislavy/assets/28804184/a759f208-a2a0-4077-a8ca-516a72b6368b

2023-06-09 07:36 UTC, eronisko requested changes
Thanks for the changes, please see some minor notes

2023-06-09 07:36 UTC, eronisko commented on resources/js/components/search/Map.vue
> +        class="-mx-4 lg:-ml-14 lg:mr-14 relative flex-shrink-0 transition-all duration-75 ease-linear"
1. Please move the margin classes outside of the element.
2. Please remove the transitions so that the map does not flash. There's a more [involved method](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#resize) for resizing the map smoothly, but I think having it jump is okay

2023-06-09 07:36 UTC, eronisko commented on resources/js/components/search/Map.vue
> +                @click="handleExpandVertically(!expandedVertically)"
Even the old method was fine IMHO, with the watcher on vertical expand
```suggestion
                @click="expandedVertically = !expandedVertically"
```

2023-06-09 07:36 UTC, eronisko commented on resources/js/components/ArtworksMasonry.vue
> +        containerResizeObserver.observe(this.$refs.container)
Please unsubscribe the observer on un-mount

2023-06-27 08:47 UTC, FrantisekMichalSebestyen commented on resources/js/components/search/Map.vue
> +                @click="handleExpandVertically(!expandedVertically)"
It adds a bit of unnecessary complexity.
If there was any other way to trigger/change expand variable, I'd agree with you.

2023-06-27 08:48 UTC, FrantisekMichalSebestyen commented on resources/js/components/search/Map.vue
> +                class="hidden lg:block absolute bottom-12 p-3 right-4 bg-white"
I tried sticky styling, but I couldn't solve it in a reasonable time.

2023-06-29 08:33 UTC, eronisko approved these changes
LGTM, thank you

2023-06-29 08:33 UTC, eronisko commented on resources/js/components/search/Map.vue
> +        toggleExpandHorizontally() {
```suggestion
        toggleExpandedHorizontally() {
```

2023-06-29 08:33 UTC, eronisko commented on resources/js/components/search/Map.vue
> +        toggleExpandVertically() {
```suggestion
        toggleExpandedVertically() {
```

2023-06-30 08:23 UTC, merged